# Generated by Django 3.0.2 on 2020-02-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='week_age',
            field=models.IntegerField(default=0),
        ),
    ]
