# Generated by Django 3.0.2 on 2020-01-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0002_auto_20200120_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='week_age',
        ),
    ]
