# Generated by Django 3.0.2 on 2020-02-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0003_auto_20200210_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='food',
            field=models.IntegerField(default=0),
        ),
    ]
