# Generated by Django 3.0.2 on 2020-01-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0003_remove_promotion_week_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
