# Generated by Django 3.0.2 on 2020-02-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0004_promotion_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='age_days',
            field=models.IntegerField(default=0),
        ),
    ]
