# Generated by Django 3.0.2 on 2020-02-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0005_promotion_age_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='entry_date',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
