# Generated by Django 3.0.2 on 2020-01-18 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'Produccion'), ('L', 'Levante')], max_length=2)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.Farm')),
            ],
            options={
                'verbose_name': 'Shed',
                'verbose_name_plural': 'Sheds',
            },
        ),
        migrations.CreateModel(
            name='ShedRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('food_income', models.IntegerField(default=0)),
                ('food_deposit', models.IntegerField()),
                ('food_consumption', models.IntegerField()),
                ('final_deposit', models.IntegerField()),
                ('chicken_quantity', models.IntegerField()),
                ('chicken_death', models.IntegerField(default=0)),
                ('chicken_total', models.IntegerField()),
                ('observation', models.TextField(blank=True)),
                ('package_total', models.IntegerField(blank=True)),
                ('leftover_eggs', models.IntegerField(blank=True)),
                ('food_type', models.CharField(choices=[('G', 'Granos'), ('M', 'Maiz')], max_length=1)),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posture_percentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('convertion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chicken_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('shed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheds.Shed')),
            ],
        ),
    ]
