# Generated by Django 3.0.2 on 2020-02-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shedregister',
            name='chicken_income',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='shedregister',
            name='chicken_initial',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='shedregister',
            name='egg_break',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shedregister',
            name='egg_dirty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shedregister',
            name='egg_white',
            field=models.IntegerField(default=0),
        ),
    ]
