# Generated by Django 3.0.2 on 2020-02-12 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheds', '0002_auto_20200210_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedregister',
            name='shed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shedregister', to='sheds.Shed'),
        ),
    ]
