# Generated by Django 3.0.2 on 2020-01-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheds', '0002_auto_20200120_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedregister',
            name='chicken_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='shedregister',
            name='convertion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='shedregister',
            name='food_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shedregister',
            name='leftover_eggs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shedregister',
            name='package_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shedregister',
            name='posture_percentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
