# Generated by Django 3.0.2 on 2020-01-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheds', '0003_auto_20200123_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='shedregister',
            name='egg_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='shedregister',
            name='food_type',
            field=models.CharField(blank=True, choices=[('G', 'Granos'), ('M', 'Maiz')], max_length=1),
        ),
    ]
