# Generated by Django 3.0.2 on 2020-02-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheds', '0003_auto_20200212_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedregister',
            name='chicken_initial',
            field=models.IntegerField(default=0),
        ),
    ]
