# Generated by Django 3.0.2 on 2020-01-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheds', '0004_auto_20200123_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shed',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
