# Generated by Django 3.0.2 on 2020-02-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheds', '0004_auto_20200214_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='shedregister',
            name='entry_chicken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shedregister',
            name='quantity_chicken',
            field=models.IntegerField(default=0),
        ),
    ]
