# Generated by Django 3.0.2 on 2020-01-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheds', '0005_auto_20200127_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shed',
            options={'ordering': ('-type', 'farm'), 'verbose_name': 'Shed', 'verbose_name_plural': 'Sheds'},
        ),
        migrations.AlterField(
            model_name='shed',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
