# Generated by Django 3.0.2 on 2020-02-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheds', '0005_auto_20200221_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='shedregister',
            name='leave_chicken',
            field=models.IntegerField(default=0),
        ),
    ]
