# Generated by Django 3.0.2 on 2020-02-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheds', '0006_shedregister_leave_chicken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shed',
            name='name',
            field=models.IntegerField(),
        ),
    ]
